### ISSUE TITLE
[BUG] Having header defined without any data causes 2 blank spaces.

### ISSUE THREAD

**Issue by andreas-aman** [tj-actions/auto-doc#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

2 blank rows are added if there isn't any documentation to add and a Header is defined.

This is true for both actions and reusable workflows.

### To Reproduce

If you add a header ex. `## Outputs` but the action or reusable workflow does not have any outputs defined 2 newlines will be added after the header for each run of auto-doc.

```
## Outputs
```

becomes

```
## Outputs


```

and after 3rd run

```
## Outputs




```

It's the same for Inputs and Secrets

### What OS are you seeing the problem on?

all

### Expected behavior?

If there is no data to add the documentation should remain unchanged.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andreas-aman** [comment]
I might've accidentally used the wrong binary 😊

**Comment by jackton1** [comment]
@palesnia Can you create a public repo that replicates this issue?

I ran a test [here](https://github.com/tj-actions/auto-doc/pull/489) and I don’t see multiple spaces

**Comment by vincentclee** [comment]
I ran into this exact issue. I didn't have outputs so i removed the block. I can create a public repo on a cron to highlight the issue.

**Comment by vincentclee** [comment]
@jackton1 I created a public repo that replicates this issue. Thank you for creating this project. I use it a lot internally.

https://github.com/vincentclee/ultra-reusable-workflow
