### ISSUE TITLE
[BUG] auto-doc replaces first occurrence of header regardless of placement.

### ISSUE THREAD

**Issue by andreas-aman** [tj-actions/auto-doc#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

auto-doc replaces the first occurrence of the header regardless of where it is.

So this section

```markdown
This is reference to ## Outputs header, this part will be removed.

## Outputs
```

Actually becomes

```markdown
This is reference to ## Outputs

<!-- AUTO-DOC-OUTPUT:START - Do not remove or modify this section -->

| OUTPUT |  TYPE  | DESCRIPTION |
|--------|--------|-------------|
|  test  | string |    test     |

<!-- AUTO-DOC-OUTPUT:END -->

## Outputs
```

### To Reproduce

Simply add a header in a different location.

### What OS are you seeing the problem on?

all

### Expected behavior?

I expect auto-doc to only replace actual headers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Thanks @andreas-aman for the fix I found some issues with other parts related to this it should now be resolved in the latest release.
