### ISSUE TITLE
[BUG] Not inserting into output file

### ISSUE THREAD

**Issue by joraff** [tj-actions/auto-doc#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Auto-doc isn't inserting into the output file for a composite action. It just returns successfully with the output "Successfully generated documentation".

I replaced my `action.yml` file with yours from `test/action.yml` with the same result. Am I missing a required input?

Thank you.

### To Reproduce

macOS 13.2.1 darwin_arm64 via homebrew
v2.5.4

```bash
$ touch README.md
$ auto-doc -f action.yml
Successfully generated documentation
$ echo $?
0
$ cat README.md
$
```

### What OS are you seeing the problem on?

macos-latest or macos-10.15

### Expected behavior?

Tables to be inserts into output file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@joraff You need to specify the headers before running auto-doc

```
## Inputs


## Outputs
```

**Comment by joraff** [comment]
🤦  I read the usage docs as "**_Adds_** the Inputs and/or Outputs...", as in the tool added it. Sorry! And thanks for the quick response.
