### ISSUE TITLE
[Feature] Optionally define headers to look for (not just `## Inputs` and `## Outputs`)

### ISSUE THREAD

**Issue by ps-jay** [tj-actions/auto-doc#514]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I'd like it if I could tell auto-doc what headers to look for

Maybe it could be `h3`, or maybe it could include emoji, or both! eg.

```
### 📥 Inputs
```

### Describe the solution you'd like?

I'd hope this could be implemented by adding some new flags to the CLI...

e.g.

```
--inputHeader '### 📥 Inputs'
```

### Describe alternatives you've considered?

None, sorry ..  this is just what I came up with off the top of my head

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Emoji’s are supported provided they appear after the header e.g

`## Inputs 📤`

**Comment by ps-jay** [comment]
Oh!  Nice

Thanks for the tip
