### ISSUE TITLE
[BUG] CLI not outputting anything

### ISSUE THREAD

**Issue by JSNortal** [tj-actions/auto-doc#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I've tried installing `auto-doc` threw brew on my machine to test out and ran the command

```bash
auto-doc -f action.yaml --reusable -o test.md
```

on a local copy of https://github.com/tj-actions/auto-doc/blob/main/test/reusable-action.yml file.

Maybe I'm miss reading how this tool is supposed to work but I'm expecting it to output a table to the `test.md` file

I've then tried downloading the latest release and running it from that binary to make sure its not a brew issue. But same thing, no output.

### To Reproduce

1. M1 Mac `brew install tj-actions/tap/auto-doc`
2. Download a copy of https://github.com/tj-actions/auto-doc/blob/main/test/reusable-action.yml file
3. auto-doc -f action.yaml --reusable -o test.md

### What OS are you seeing the problem on?

macos-latest or macos-12

### Expected behavior?

Expecting something outputted to the `test.md` file

### Relevant log output

```shell
none
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @JSNortal, I’ll suggest updating the `test.md` with any of the [support headings](https://github.com/tj-actions/auto-doc?tab=readme-ov-file#supported-headings).

**Comment by devSarry** [comment]
Ahh ok I didn't quite understand the readme. Thanks, I got it now.
